name: flutter_admin
description: 一个基于flutter的后台管理系统 - A management system based on flutter
version: 1.0.0+1

environment:
  sdk: ">=2.2.2 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  dio: 3.0.7
  cupertino_icons: ^0.1.2
  charts_flutter: ^0.8.0
  flutter_custom_clippers: ^1.1.0
  cached_network_image: ^2.0.0-rc
  font_awesome_flutter: ^8.5.0
  json_annotation: ^2.2.0
  bot_toast: ^2.2.1
  flutter_colorpicker: any
  flutter_localizations:
    sdk: flutter
  intl_translation: null
  intl: null
  url_launcher: ^5.4.1
  universal_html: ^1.2.2
  mime_type: ^0.3.1
  image_picker: ^0.6.7
  image_picker_for_web: ^0.1.0
  video_player: ^0.10.5
  quiver: ^2.1.3
  cry: ^0.0.4


dev_dependencies:
  flutter_test:
    sdk: flutter
  json_model: #latest version
    null
  json_serializable: ^2.0.0
  build_runner: ^1.0.0
flutter:
  uses-material-design: true
flutter_intl:
  enabled: true
